env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: babel-eslint
plugins:
  - react
rules: {
  linebreak-style: [error, windows],
  camelcase: off,
  no-console: off,
  no-multi-assign: off,
  no-plusplus: off,
  import/prefer-default-export: off,
  import/extensions: [
    error,
    ignorePackages,
    {
      js: never,
      jsx: never,
      ts: never,
      tsx: never
    }
  ],
  import/no-extraneous-dependencies: off
}
